name: Compatibility Check

on:
  schedule:
    - cron: '0 2 * * 0'  # Every Sunday at 2 AM
  workflow_dispatch:  # Manual trigger

jobs:
  compatibility:
    name: OCaml Compatibility
    runs-on: ubuntu-22.04
    
    strategy:
      matrix:
        ocaml-version: [4.12, 4.13, 4.14, 5.0, 5.1, 5.2]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Use OCaml ${{ matrix.ocaml-version }}
      uses: ocaml/setup-ocaml@v2
      with:
        ocaml-compiler: ${{ matrix.ocaml-version }}
        opam-depext: false
        
    - name: Install dependencies
      run: |
        opam update
        opam install . --deps-only --with-test
        
    - name: Build project
      run: dune build
        
    - name: Run tests
      run: dune runtest
        
    - name: Run Zobrist tests
      run: _build/default/test/test_zobrist.exe
        
    - name: Build examples
      run: dune build examples/
        
    - name: Run demos
      run: |
        _build/default/examples/pgn_demo.exe
        _build/default/examples/board_demo.exe
        _build/default/examples/zobrist_demo.exe
