name: Compatibility Check

on:
  schedule:
    - cron: '0 2 * * 0'  # Every Sunday at 2 AM
  workflow_dispatch:  # Manual trigger

jobs:
  compatibility:
    name: OCaml Compatibility
    runs-on: ubuntu-22.04
    timeout-minutes: 20
    env:
      OPAMYES: "1"
      OPAMNO: "1"
      OPAMVERBOSE: "1"
    
    strategy:
      matrix:
        ocaml-version: [4.14]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install OCaml ${{ matrix.ocaml-version }} manually
      run: |
        echo "Installing OCaml ${{ matrix.ocaml-version }} manually..."
        
        # Add OPAM repository
        sudo add-apt-repository ppa:avsm/ppa -y || true
        sudo apt-get update || true
        
        # Install OPAM
        sudo apt-get install -y opam || true
        
        # Initialize OPAM
        opam init --disable-sandboxing --yes
        
        # Update OPAM
        opam update
        
        # List available OCaml versions
        echo "Available OCaml versions:"
        opam switch list-available | grep -E "ocaml\.[0-9]" | head -10
        
        # Install OCaml
        opam switch create ${{ matrix.ocaml-version }} ocaml.${{ matrix.ocaml-version }}.0 --yes
        opam switch ${{ matrix.ocaml-version }}
        echo "OCaml ${{ matrix.ocaml-version }} installed successfully"
        
    - name: Install dependencies
      run: |
        eval $(opam env)
        opam update
        opam install . --deps-only --with-test
        
    - name: Build project
      run: |
        eval $(opam env)
        dune build
        
    - name: Run tests
      run: |
        eval $(opam env)
        dune runtest
        
    - name: Run Zobrist tests
      run: |
        eval $(opam env)
        _build/default/test/test_zobrist.exe
        
    - name: Build examples
      run: |
        eval $(opam env)
        dune build examples/
        
    - name: Run demos
      run: |
        eval $(opam env)
        _build/default/examples/pgn_demo.exe
        _build/default/examples/board_demo.exe
        _build/default/examples/zobrist_demo.exe
