name: Deploy Documentation

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install OCaml manually
        run: |
          echo "Installing OCaml 4.14 manually..."
          
          # Add OPAM repository
          sudo add-apt-repository ppa:avsm/ppa -y || true
          sudo apt-get update || true
          
          # Install OPAM
          sudo apt-get install -y opam || true
          
          # Initialize OPAM
          opam init --disable-sandboxing --yes
          
          # Update OPAM
          opam update
          
          # List available OCaml versions
          echo "Available OCaml versions:"
          opam switch list-available | grep -E "ocaml\.[0-9]" | head -10
          
          # Install OCaml
          opam switch create 4.14 ocaml.4.14.0 --yes
          opam switch 4.14
          
          echo "OCaml 4.14 installed successfully"
          
      - name: Install dependencies
        env:
          OPAMYES: "1"
          OPAMNO: "1"
          OPAMVERBOSE: "1"
        run: |
          echo "Cleaning OPAM cache..."
          timeout 300 opam update
          echo "Installing dune..."
          timeout 300 opam install dune --yes
          echo "Installing project dependencies..."
          timeout 600 opam install . --deps-only --with-test --with-doc --yes
          echo "Dependencies installed successfully"
          
          # Update shell environment
          eval $(opam env)
          echo "Shell environment updated"
          
      - name: Build OCaml documentation
        run: |
          eval $(opam env)
          dune build @doc
          
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: false
          
      - name: Setup Jekyll
        run: |
          cd docs
          gem install bundler --user-install
          bundle config set --local path 'vendor/bundle'
          bundle install
          
      - name: Build Jekyll site
        run: |
          cd docs
          bundle config set --local path 'vendor/bundle'
          bundle exec jekyll build --destination ../_site
          
      - name: Copy OCaml docs to Jekyll site
        run: |
          mkdir -p _site/api
          cp -r _build/default/_doc/_html/* _site/api/
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: '_site'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
